[package]
name = "mediaconverter"
version = "0.1.0"
description = "A Media Converter app based on svelte and Tauri"
authors = ["sajadb-dev"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "mediaconverter_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ffmpeg-next = "7.1.0"
ffmpeg-sys-next = "7.1.0"
pkg-config = "0.3.32"
tauri-plugin-dialog = "2"
image = "0.25.0"

